### PR TITLE
Add Creator Mode and initial features

### PR DESCRIPTION
**Pull request by Amadeus-**
First, please note that this code only adds new features, it does not remove or change any existing features.

Basically, this pull request will add a new feature to the addon called "Creator Mode".   The idea for this mode is simply that, with it enabled, those who are creating and/or editing guides will receive additional information in the chat window which would not normally be of interest to regular players.   As of this pull request, the only thing it does is add the features mentioned below.

To TOGGLE "Creator Mode" simply type `/zgv creator` in the chat window.   You will see where it tells you whether you've toggled it on or off.   This setting is saved and will persist until it's changed again via the chat window command.   Please note that it is OFF by default.

"Creator Mode" is intended to provide useful information to those who are creating or editing guides.  It will not serve as a substitute for being familiar with the format of the guides.   Truly, it's just to minimize the need to be looking at other online sources of information by providing that data directly to the player as they play through the game.   For now, there are three things included with "Creator Mode" (with plans for more to be added later on):

### Lorebook Information
When you click on any lorebook in the game (that you have not read previously) you will receive a chat message in bright yellow that looks like how you would use it in the guide:
Lorebook
Please note that you will get this message for all lorebooks the **first** time they're read, including "bookshelves".

### Achievement Completion
When you complete an achievement, you'll receive the following notification.   This is useful for things like exploring delves, amongst other things.
Achievements

### Skyshards
Guides which involve the clicking of skyshards utilize checking achievements with multiple criteria.   So, what you have to use is the achievement number plus the exact criterion number for the skyshard in question.   This new feature will provide you with the syntax that is most often used in the guides (in bright yellow), and then give you a list of the skyshards which you have completed thus far in the zone (which will include the one you just clicked.)   If you're progressing through a zone and keep track of all skyshards you click, the new line that appears in this list each time will always be the one you want.
Achievements

### CODE REVIEW

**Comment by Amadeus-** [comment]
I plan to also add things related to the actual quests and quest steps soon, etc.

**Comment by Gator7778** [comment]
I also learned you don't need a new step for every goto function so I plan on redoing alot of the 9ld guides and even my own guides I found from a typo

**Comment by Amadeus-** [comment]
Yea, I'm basically following through guides as I go, and seeing what would be useful to have as a creator/editor.  I'm also wanting to do some research to see if something that was added after 2014 might reduce the need for so many of the "skip to the next step manually after doing whatever" that's in the original guides.

By the way, I used Zygor in World of Warcraft since they started making them there.  I played ESO a little at launch, with the guides Zygor released, but then got bored with the game.   I just now returned back to ESO and am enjoying it a lot more.   So, since I'm leveling up, I figured I'd help with the guides while I was at it.

**Comment by Gator7778** [comment]
i've removed a whole shit ton of skips that will be in my next guide release im doing all the expansions or was before video card went down ive completed most im upto Northern Elsweyr and ive gone in the order they were released

**Comment by Amadeus-** [comment]
Is there anything specific that the addon could tell you, as you're playing through, that would help in editing or making new guides, that it doesn't now?   Perhaps things that you have to look up on another website?  (such as the lorebook and skyshards stuff I added in this pull request?)

**Comment by Gator7778** [comment]
yea i noticed that in that screen shot and yes when authoring guides i have to go eso armory website to get the achievement numbers for skyshards and delves and i got a notepad on my pc with the lorebooks then i have to keep playing trial and error to figure out which number lorebook in the series it is

**Comment by Amadeus-** [comment]
Is there anything else that would be helpful when authoring?   Anything else that would reduce having to go to other websites?

**Comment by Gator7778** [comment]
i cant think of anything right off the top of my head but that right there will be a huge time saver now that ive taken a closer look at it.

**Comment by Amadeus-** [comment]
I updated the Skyshard event notification (Feature #3 in the initial posting above) so that it only lists completed skyshards.  In other words, it will only list possible skyshards for the current event, not all of them as I showed in my original posting.

I'll try and get a screenshot to update my original posting on this pull request soon.   It looks/works the same, it's just that the list will only have those skyshards that it COULD be.   So, for the first skyshard you click on in a zone, there will only be one possibility ...then, on the second you click, there will be two (since it only lists those you've completed ...which includes the **current** one.)   In other words, as long as you're keeping track as you go, it should be pretty easy to pick the correct number for the line in the guide :)

**Comment by Gator7778** [comment]
i should be back in tomorrow or Tuesday stupid video card went from china to japan to now Memphis which is a 2 hour drive

**Comment by Gator7778** [comment]
conflict cant merge lines 85-89 in options.lua github wont merge 
<<<<<<< CreatorMode
  creator = false,
=======
  developer = false,
>>>>>>> master

after i get everything reinstalled ill see what i can to force it to merge

**Pull request merged**
